console.log("Arithmetic Operators");
let a = 10; b=5;
console.log("a+b = ",a+b);
console.log("a-b = ",a-b);
console.log("a*b = ",a*b);
console.log("a/b = ",a/b);
console.log("a%b = ",a%b);
console.log("a**b = ",a**b);
console.log("a++ = ",a++);
console.log("a-- = ",a--);
console.log("++a = ",++a);
console.log("--a = ",--a);
console.log("Assignment Operators");
console.log("Assignment Operators");
let x = 10;
x += 5;
console.log("x = x+5 ->",x);
x -= 5;
console.log("x = x-5 ->",x);
console.log("bitwise Operators");
console.log("5 $ 1 ->",5&1);
console.log("5 | 1 ->",5|1);    
console.log("5 ^ 1 ->",5^1);
console.log("~5 ->",~5);
console.log("5 << 1 ->",5<<1);
console.log("5 >> 1 ->",5>>1);
console.log("5 >>> 1 ->",5>>>1);
console.log("Logical Operators");
let age = 20;
let status = (age>=18)?"Adult":"Child";
console.log("status ->",status);
console.log("Type Operators");
console.log("typeof 5 ->",typeof 5);
console.log("tpye of 'hello' ->",typeof 'hello');
console.log("type of true ->",typeof true);
console.log("type of {} ->",typeof {});
console.log("type of [] ->",typeof []);
console.log("instance operator");
let arr =[1,2,3];
console.log("arr instanceof Array ->",arr instanceof Array);
console.log("arr instanceof Object ->",arr instanceof Object);

